https://api.giphy.com/v1/gifs/trending?api_key=bFRAbs0NV8UEeYQqnr4SyLatKbIs81KY&limit=10&rating=g

###
https://api.giphy.com/v1/gifs/trending?api_key=bFRAbs0NV8UEeYQqnr4SyLatKbIs81KY&limit=10&rating=g/data/1/title